version: '3.9'

services:
  app:
    ports:
      - "8000:8000"
    volumes:
      - .:${VOLUME_PATH}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mysql+aiomysql://root:root1234$@db:3306/blog_db
      - IMAGE_UPLOAD_PATH=${VOLUME_PATH}/src/static/images
      - VOLUME_PATH=${VOLUME_PATH}
      - SECRET_KEY=bolg_db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=blog_db
      - MYSQL_ROOT_PASSWORD=root1234$
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot1234$" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
