"""commit2

Revision ID: 23affecf9d51
Revises: 
Create Date: 2025-08-28 13:35:54.126500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '23affecf9d51'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog', 'title',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('blog', 'content',
               existing_type=mysql.VARCHAR(length=4000),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('blog', 'image_loc',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_blog_id'), 'blog', ['id'], unique=False)
    op.create_foreign_key(None, 'blog', 'user', ['author_id'], ['id'])
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('email'), table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index(op.f('email'), 'user', ['email'], unique=True)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_constraint(None, 'blog', type_='foreignkey')
    op.drop_index(op.f('ix_blog_id'), table_name='blog')
    op.alter_column('blog', 'image_loc',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=300),
               existing_nullable=True)
    op.alter_column('blog', 'content',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=4000),
               existing_nullable=False)
    op.alter_column('blog', 'title',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###
