"""자기참조 comment 테이블 생성

Revision ID: b4319c0a29a9
Revises: 93a5e519dfc1
Create Date: 2025-08-29 10:27:58.729588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4319c0a29a9'
down_revision: Union[str, Sequence[str], None] = '93a5e519dfc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('comment', sa.Column('blog_id', sa.Integer(), nullable=False))
    op.add_column('comment', sa.Column('author_id', sa.Integer(), nullable=False))
    op.add_column('comment', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_comment_id'), 'comment', ['id'], unique=False)
    op.create_foreign_key(None, 'comment', 'comment', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'blog', ['blog_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_index(op.f('ix_comment_id'), table_name='comment')
    op.drop_column('comment', 'parent_id')
    op.drop_column('comment', 'author_id')
    op.drop_column('comment', 'blog_id')
    op.drop_column('blog', 'created_at')
    # ### end Alembic commands ###
