"""이메일 인증 필드 추가

Revision ID: ef5762bcf479
Revises: 7bacef977a7a
Create Date: 2025-09-15 00:18:03.793020

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ef5762bcf479"
down_revision: str | Sequence[str] | None = "7bacef977a7a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("is_email_verified", sa.Boolean(), nullable=True, default=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_email_verified")
    # ### end Alembic commands ###
